
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  idLogin: 'idLogin',
  nome: 'nome',
  cognome: 'cognome',
  email: 'email',
  password: 'password',
  societa: 'societa',
  tecnicocod: 'tecnicocod',
  attivo: 'attivo',
  typeutente: 'typeutente',
  colore: 'colore'
};

exports.Prisma.ClienteScalarFieldEnum = {
  id: 'id',
  codicecliente: 'codicecliente',
  idazienda: 'idazienda'
};

exports.Prisma.ClienteContattoScalarFieldEnum = {
  id: 'id',
  idcliente: 'idcliente'
};

exports.Prisma.ClienteContrattoScalarFieldEnum = {
  id: 'id',
  idcliente: 'idcliente'
};

exports.Prisma.ClienteNotaScalarFieldEnum = {
  id: 'id',
  idcliente: 'idcliente'
};

exports.Prisma.ClienteProdottoScalarFieldEnum = {
  id: 'id',
  idcliente: 'idcliente',
  idprodotto: 'idprodotto'
};

exports.Prisma.OperazioneScalarFieldEnum = {
  id: 'id',
  datacreazione: 'datacreazione',
  tipo: 'tipo',
  codice: 'codice',
  anno: 'anno',
  idazienda: 'idazienda',
  idcliente: 'idcliente',
  idintervento: 'idintervento',
  operatore: 'operatore',
  idprodotto: 'idprodotto',
  dataesecuzione: 'dataesecuzione',
  orainizio: 'orainizio',
  orafine: 'orafine',
  totaleore: 'totaleore',
  osservazioni: 'osservazioni',
  codicecliente: 'codicecliente',
  stato: 'stato',
  eliminato: 'eliminato',
  idprodottocliente: 'idprodottocliente',
  faseoperazione: 'faseoperazione'
};

exports.Prisma.OperazioneFirmaScalarFieldEnum = {
  id: 'id',
  idoperazione: 'idoperazione'
};

exports.Prisma.OperazioneDescrizazioniScalarFieldEnum = {
  id: 'id',
  idoperazione: 'idoperazione'
};

exports.Prisma.OperazionePutazioneScalarFieldEnum = {
  id: 'id',
  idoperazione: 'idoperazione'
};

exports.Prisma.ProdottoScalarFieldEnum = {
  id: 'id',
  nome: 'nome'
};

exports.Prisma.ProdottoVoceScalarFieldEnum = {
  id: 'id',
  idprodotto: 'idprodotto'
};

exports.Prisma.ContrattoScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  denominazione: 'denominazione',
  tipodurata: 'tipodurata',
  durata: 'durata',
  avvprima: 'avvprima',
  avvdopo: 'avvdopo',
  cancellato: 'cancellato'
};

exports.Prisma.PianningTipoInterventoScalarFieldEnum = {
  id: 'id'
};

exports.Prisma.PianningEmailScalarFieldEnum = {
  id: 'id',
  idlogin: 'idlogin'
};

exports.Prisma.VociInterventoScalarFieldEnum = {
  id: 'id'
};

exports.Prisma.StraordinarioScalarFieldEnum = {
  id: 'id'
};

exports.Prisma.InserimentoStraordinarioScalarFieldEnum = {
  id: 'id'
};

exports.Prisma.ImpostazioniUtenteScalarFieldEnum = {
  id: 'id'
};

exports.Prisma.SpeseNottiScalarFieldEnum = {
  id: 'id'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Cliente: 'Cliente',
  ClienteContatto: 'ClienteContatto',
  ClienteContratto: 'ClienteContratto',
  ClienteNota: 'ClienteNota',
  ClienteProdotto: 'ClienteProdotto',
  Operazione: 'Operazione',
  OperazioneFirma: 'OperazioneFirma',
  OperazioneDescrizazioni: 'OperazioneDescrizazioni',
  OperazionePutazione: 'OperazionePutazione',
  Prodotto: 'Prodotto',
  ProdottoVoce: 'ProdottoVoce',
  Contratto: 'Contratto',
  PianningTipoIntervento: 'PianningTipoIntervento',
  PianningEmail: 'PianningEmail',
  VociIntervento: 'VociIntervento',
  Straordinario: 'Straordinario',
  InserimentoStraordinario: 'InserimentoStraordinario',
  ImpostazioniUtente: 'ImpostazioniUtente',
  SpeseNotti: 'SpeseNotti'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
